font.size:50
bold.numbers:false
autosave.stats:false
reverse.validated.colors:false
save.path:.
font.name:Tahoma
normal.background:240,240,240
dark.background:200,200,200
light.background:250,250,250
normal.font.color:0,0,0
invalid.font.color:255,0,0
valid.font.color:0,200,0
language.name:french
standby.default:true
standby.return:false
standby.wait:15
standby.zoom:2.5
standby.path:.
